/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Université Demo API
 * OpenAPI spec version: 1.0.0
 */

export interface Cours {
  mnemonique?: string;
  intitule?: string;
  credit?: number;
  titulaire?: string;
}
