/**
 * Generated by orval v7.11.2 🍺
 * Do not edit manually.
 * Université Demo API
 * OpenAPI spec version: 1.0.0
 */

export interface Inscription {
  matricule?: string;
  nom?: string;
  prenom?: string;
  annee_etude?: number;
  cours_json?: string;
}
